# Lychee configuration for fast, reliable link checking
# Speed & resilience
max_concurrency = 8
timeout = 20 # seconds (numeric)
retries = 2
retry_wait_time = 5 # seconds (numeric)

# Acceptable HTTP codes
accept = [200, 204, 206, 301, 302, 307, 308]

# Exclusions
exclude = [
    "mailto:",
    "tel:",
    "http://localhost:",
    "https://localhost:",
    "http://127.0.0.1:",
    "https://127.0.0.1:",
    "http://0.0.0.0:",
    "https://0.0.0.0:",
    ".localhost",
    ".test"
]
