# Lychee configuration for fast, reliable link checking
# Speed & resilience
max_concurrency = 8
timeout = "20s"
retries = 2
retry_wait_time = "5s"

# Ignore common non-web schemes and local hosts
exclude = [
    "mailto:",
    "tel:",
    "http://localhost:",
    "https://localhost:",
    "http://127.0.0.1:",
    "https://127.0.0.1:",
    "http://0.0.0.0:",
    "https://0.0.0.0:",
    ".localhost",
    ".test"
]

# Consider 429/5xx transient
accept = ["200", "204", "206", "301", "302", "307", "308"]

# Save a report
output = "lychee-report.md"
