name: Fast Link Check

on:
  pull_request:
    paths:
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Lychee
        uses: actions/cache@v4
        with:
          path: ~/.cache/lychee
          key: lychee-${{ runner.os }}-${{ hashFiles('**/*.md', 'lychee.toml') }}
          restore-keys: |
            lychee-${{ runner.os }}-

      - name: Get changed markdown files
        id: changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.md

      - name: Run Lychee on changed files
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --config lychee.toml
            ${{ steps.changes.outputs.all_changed_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # If no changed files, skip
        if: ${{ steps.changes.outputs.any_changed == 'true' }}

      - name: No markdown changes
        if: ${{ steps.changes.outputs.any_changed != 'true' }}
        run: |
          echo "No Markdown changes detected. Skipping link check." | tee lychee-report.md

      - name: Upload Lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee-report.md
          if-no-files-found: warn

      - name: Write job summary
        if: always()
        run: |
          echo "## Markdown Link Check" >> $GITHUB_STEP_SUMMARY
          if [ -f lychee-report.md ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Report attached as artifact **lychee-report**." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo 'If the job failed, open the artifact to see broken links.' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Comment on PR (same-repo only)
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = "✅ Link check completed. See artifact **lychee-report** for details.";
            if (process.env['STATE_lychee_exitcode'] === '1') {
              body = "❌ Link check found issues. See artifact **lychee-report** for details.";
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            })
